github:
  urls:
    env: 'https://api.github.com'

spotify:
  urls:
    play: 'https://open.spotify.com'
    auth: 'https://accounts.spotify.com'
    search: 'https://api.spotify.com/v1'
  limits:
    rate: 3
    query: 50

sonos:
  urls:
    auth: 'https://api.sonos.com/login/v3'
    control: 'https://api.ws.sonos.com/control/api/v1'
    
soundcloud:
  urls:
    play: 'https://soundcloud.com'
    widget: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com'
    search: 'https://api-v2.soundcloud.com'
  limits:
    rate: 0.5
    query: 24

azure:
  urls:
    login: 'https://login.microsoftonline.com/common/oauth2/v2.0'
    graph: 'https://graph.microsoft.com/v1.0'
  limits:
    rate: 5

musicbrainz:
  urls:
    search: 'https://musicbrainz.org/ws/2'
  limits:
    rate: 1
    qhar: 100

billboard:
  limits:
    rate: 1

gcp:
  urls:
    auth: 'https://accounts.google.com'
    apis: 'https://www.googleapis.com'
    token: 'https://oauth2.googleapis.com/token'

lastfm:
  urls:
    search: 'https://ws.audioscrobbler.com/2.0'
  limits:
    rate: 1  

youtube:
  urls:
    auth: 'https://accounts.google.com/o/oauth2/auth'
    token: 'https://oauth2.googleapis.com/token'
    cert: 'https://www.googleapis.com/oauth2/v1/certs'
