spotify:
  sources: [albums, playlists, favorites]
  explicits: True
  various_artists_id: 0LyfQWJT6nXafLPZqxe9Of
  audio_analysis: True

sonos:
  sources: [playlists, favorites]

soundcloud:
  sources: [albums, favorites]

onedrive:
  sources: [albums]