name: LIBRARY - Update with additional information from Spotify and MusicBrainz

on:
  schedule:
    - cron: '0 15 * * *'
    
jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: digitalvinyls

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Update library information   
      env:
        NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTFY_CLIENT_SECRET }}
        
      run: |
        python pull_library.py
