name: CHART - Update Billboard Charts

on:
  schedule:
    - cron: '0 5 * * 3'
    
jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: digitalvinyls

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check Billboard for the latest Billboard 200 chart     
      env:

        NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
      run: |
        python -c 'import chart; chart.main(critics=False, charts=True)'
